export const FETCH_POKEMONS = 'FETCH_POKEMONS'
export const FETCH_POKEMONS_SUCCESS = 'FETCH_POKEMONS_SUCCESS'
export const FETCH_POKEMONS_FAIL = 'FETCH_POKEMONS_FAIL'

export const GET_PAGE_ITEMS = 'GET_PAGE_ITEMS'
