export const FETCH_POKEMONS = 'FETCH_POKEMONS'
export const FETCH_POKEMONS_SUCCESS = 'FETCH_POKEMONS_SUCCESS'
export const FETCH_POKEMONS_FAIL = 'FETCH_POKEMONS_FAIL'

export const SET_POKEMON_PAGING = 'SET_POKEMON_PAGING'
export const SET_CATEGORY_PAGING = 'SET_CATEGORY_PAGING'
